const state={ingredients:[],recipes:[],selectedRecipeId:null,relations:[]};
const $=s=>document.querySelector(s),fmt=n=>new Intl.NumberFormat('es-CU',{maximumFractionDigits:2}).format(n),money=n=>new Intl.NumberFormat('es-CU',{style:'currency',currency:'CUP',minimumFractionDigits:2}).format(n);
const esc=v=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function msg(b){if(Array.isArray(b))return b.map(x=>x.errorMessage||x).join(' · ');if(b&&typeof b==='object')return b.message||b.title||Object.values(b).flat().join(' · ');return b} 
async function api(path,opt={}){const r=await fetch('/api'+path,{headers:{'content-type':'application/json',...(opt.headers||{})},...opt}),ct=r.headers.get('content-type')||'',b=r.status===204?null:ct.includes('json')?await r.json():await r.text();if(!r.ok)throw Error(msg(b)||`Error HTTP ${r.status}`);return b}
let timer;function toast(text,error=false){const e=$('#toast');e.textContent=text;e.className='toast show'+(error?' error':'');clearTimeout(timer);timer=setTimeout(()=>e.className='toast',3800)}
function connected(ok){const e=$('#connection-status');e.textContent=ok?'● API conectada':'● API no disponible';e.className='connection '+(ok?'ok':'error')}
async function loadIngredients(){state.ingredients=await api('/Ingredient');$('#ingredients-body').innerHTML=state.ingredients.map(i=>`<tr><td>${esc(i.name)}</td><td>${esc(i.unit)}</td><td>${money(i.price)}</td><td class="actions"><button class="text-button" data-ei="${i.id}">Editar</button><button class="text-button delete" data-di="${i.id}">Eliminar</button></td></tr>`).join('');$('#ingredients-empty').hidden=!!state.ingredients.length}
async function loadRecipes(){state.recipes=await api('/Recipe');$('#recipes-body').innerHTML=state.recipes.map(r=>`<tr><td>${esc(r.name)}</td><td>${fmt(r.yield)} porciones</td><td class="actions"><button class="text-button" data-sr="${r.id}">Abrir</button><button class="text-button" data-er="${r.id}">Editar</button><button class="text-button delete" data-dr="${r.id}">Eliminar</button></td></tr>`).join('');$('#recipes-empty').hidden=!!state.recipes.length;productionOptions()}
function productionOptions(){const s=$('#production-recipe-selector'),current=String(state.selectedRecipeId||'');s.innerHTML='<option value="">Selecciona una receta</option>'+state.recipes.map(r=>`<option value="${r.id}">${esc(r.name)} (${r.yield} porciones)</option>`).join('');s.value=current}
function ingredientDialog(i){$('#ingredient-form').reset();$('#ingredient-id').value=i?.id||'';$('#ingredient-dialog-title').textContent=i?'Editar ingrediente':'Nuevo ingrediente';if(i){$('#ingredient-name').value=i.name;$('#ingredient-unit').value=i.unit;$('#ingredient-price').value=i.price}$('#ingredient-error').textContent='';$('#ingredient-dialog').showModal()}
function recipeDialog(r){$('#recipe-form').reset();$('#recipe-id').value=r?.id||'';$('#recipe-dialog-title').textContent=r?'Editar receta':'Nueva receta';if(r){$('#recipe-name').value=r.name;$('#recipe-yield-input').value=r.yield}$('#recipe-error').textContent='';$('#recipe-dialog').showModal()}
function relationDialog(rel){if(!state.selectedRecipeId)return;$('#recipe-ingredient-form').reset();$('#recipe-ingredient-id').value=rel?.id||'';$('#recipe-ingredient-dialog-title').textContent=rel?'Editar ingrediente':'Añadir ingrediente';const used=new Set(state.relations.filter(r=>r.id!==rel?.id).map(r=>r.ingredientId)),available=state.ingredients.filter(i=>!used.has(i.id));$('#relation-ingredient').innerHTML=available.map(i=>`<option value="${i.id}">${esc(i.name)} (${esc(i.unit)})</option>`).join('');if(rel){$('#relation-ingredient').value=rel.ingredientId;$('#relation-quantity').value=rel.quantity}$('#recipe-ingredient-error').textContent='';if(!available.length)return toast('Todos los ingredientes ya pertenecen a esta receta.',true);$('#recipe-ingredient-dialog').showModal()}
async function saveIngredient(e){e.preventDefault();const id=$('#ingredient-id').value,data={name:$('#ingredient-name').value.trim(),unit:$('#ingredient-unit').value,price:Number($('#ingredient-price').value)};try{await api('/Ingredient'+(id?'/'+id:''),{method:id?'PUT':'POST',body:JSON.stringify(data)});$('#ingredient-dialog').close();await loadIngredients();if(state.selectedRecipeId)await recipeDetail(state.selectedRecipeId);toast(id?'Ingrediente actualizado.':'Ingrediente creado.')}catch(x){$('#ingredient-error').textContent=x.message}}
async function saveRecipe(e){e.preventDefault();const id=$('#recipe-id').value,data={name:$('#recipe-name').value.trim(),yield:Number($('#recipe-yield-input').value)};try{await api('/Recipe'+(id?'/'+id:''),{method:id?'PUT':'POST',body:JSON.stringify(data)});$('#recipe-dialog').close();await loadRecipes();if(id&&state.selectedRecipeId===Number(id))await recipeDetail(id);toast(id?'Receta actualizada.':'Receta creada.')}catch(x){$('#recipe-error').textContent=x.message}}
async function saveRelation(e){e.preventDefault();const id=$('#recipe-ingredient-id').value,data={recipeId:state.selectedRecipeId,ingredientId:Number($('#relation-ingredient').value),quantity:Number($('#relation-quantity').value)};try{await api('/RecipeIngredient'+(id?'?id='+id:''),{method:id?'PUT':'POST',body:JSON.stringify(data)});$('#recipe-ingredient-dialog').close();await recipeDetail(state.selectedRecipeId);toast(id?'Ingrediente actualizado en la receta.':'Ingrediente añadido a la receta.')}catch(x){$('#recipe-ingredient-error').textContent=x.message}}
async function recipeDetail(id){state.selectedRecipeId=Number(id);const recipe=state.recipes.find(r=>r.id===state.selectedRecipeId);try{const [all,items,cost]=await Promise.all([api('/RecipeIngredient'),api(`/RecipeIngredient/${id}/Ingredients`),api(`/RecipeIngredient/${id}/Cost`)]);state.relations=all.filter(r=>r.recipeId===state.selectedRecipeId);const rel=new Map(state.relations.map(r=>[r.ingredientId,r]));$('#recipe-detail').innerHTML=`<div class="detail-heading"><div><h2>${esc(recipe?.name||cost.name)}</h2><p>Rinde ${fmt(recipe?.yield||0)} porciones.</p></div><button class="secondary" id="close-detail">Cerrar</button></div><div class="detail-cost">Costo total de la receta <strong>${money(cost.cost)}</strong></div><div class="table-wrap"><table><thead><tr><th>Ingrediente</th><th>Cantidad</th><th>Costo</th><th></th></tr></thead><tbody>${items.map(i=>{const r=rel.get(i.id);return `<tr><td>${esc(i.name)} <small>(${esc(i.unit)})</small></td><td>${fmt(i.quantity)} ${esc(i.unit)}</td><td>${money(i.cost)}</td><td class="actions"><button class="text-button" data-e-rel="${r?.id}">Editar</button><button class="text-button delete" data-d-rel="${r?.id}">Quitar</button></td></tr>`}).join('')}</tbody></table></div>${items.length?'':'<p class="empty">Aún no hay ingredientes en esta receta.</p>'}<button class="primary add-ingredient" id="add-relation">+ Añadir ingrediente</button>`;productionOptions()}catch(x){toast(x.message,true)}}
function clearDetail(){state.selectedRecipeId=null;state.relations=[];$('#recipe-detail').innerHTML='<div class="empty-state"><span>⌁</span><h2>Selecciona una receta</h2><p>Podrás gestionar sus ingredientes y consultar su costo.</p></div>';productionOptions()}
function selectProduction(id){state.selectedRecipeId=id?Number(id):null;$('#production-content').hidden=!id;$('#production-placeholder').hidden=!!id;$('#production-result').hidden=true}
async function production(e){e.preventDefault();const id=state.selectedRecipeId,p=Number($('#portions-input').value);if(!id||p<=0)return;try{const [r,items]=await Promise.all([api(`/RecipeIngredient/${id}/Production/${p}`),api(`/RecipeIngredient/${id}/Ingredients/Production/${p}`)]);$('#needed-recipes').textContent=fmt(r.recipesReals);$('#exact-recipes').textContent=`${fmt(r.recipesNecessary)} recetas exactas`;$('#remaining-portions').textContent=fmt(r.portionsRest);$('#exact-cost').textContent=money(r.exactCost);$('#real-cost').textContent=money(r.realCost);$('#necessary-ingredients-body').innerHTML=items.map(i=>`<tr><td>${esc(i.name)}</td><td>${fmt(i.cant)}</td><td>${money(i.cost)}</td></tr>`).join('');$('#production-result').hidden=false}catch(x){toast(x.message,true)}}
function loadForView(v){const task=v==='ingredients'?loadIngredients():v==='recipes'||v==='production'?loadRecipes():null;if(task)task.then(()=>connected(true)).catch(e=>{connected(false);toast('No fue posible cargar la API: '+e.message,true)})}
function view(v){['home','ingredients','recipes','production'].forEach(n=>$('#'+n+'-view').hidden=n!==v);['ingredients','recipes','production'].forEach(n=>$(`[data-view-link="${n}"]`).classList.toggle('active',n===v));if(v==='production')productionOptions();if(v!=='home')loadForView(v)}
addEventListener('hashchange',()=>view(location.hash.slice(1)||'home'));
document.addEventListener('click',async e=>{const d=e.target.dataset;if(d.closeDialog)return $('#'+d.closeDialog).close();if(d.ei)return ingredientDialog(state.ingredients.find(i=>i.id===+d.ei));if(d.er)return recipeDialog(state.recipes.find(r=>r.id===+d.er));if(d.sr)return recipeDetail(d.sr);if(d['eRel'])return relationDialog(state.relations.find(r=>r.id===+d['eRel']));if(e.target.id==='add-relation')return relationDialog();if(e.target.id==='close-detail')return clearDetail();if(d.di&&confirm('¿Eliminar este ingrediente?'))try{await api('/Ingredient/'+d.di,{method:'DELETE'});await loadIngredients();if(state.selectedRecipeId)await recipeDetail(state.selectedRecipeId);toast('Ingrediente eliminado.')}catch(x){toast(x.message,true)}if(d.dr&&confirm('¿Eliminar esta receta? También se eliminarán sus ingredientes asociados.'))try{await api('/Recipe/'+d.dr,{method:'DELETE'});await loadRecipes();if(state.selectedRecipeId===+d.dr)clearDetail();toast('Receta eliminada.')}catch(x){toast(x.message,true)}if(d['dRel']&&confirm('¿Quitar este ingrediente de la receta?'))try{await api('/RecipeIngredient?id='+d['dRel'],{method:'DELETE'});await recipeDetail(state.selectedRecipeId);toast('Ingrediente eliminado de la receta.')}catch(x){toast(x.message,true)}});
$('#new-ingredient').onclick=()=>ingredientDialog();$('#new-recipe').onclick=()=>recipeDialog();$('#ingredient-form').onsubmit=saveIngredient;$('#recipe-form').onsubmit=saveRecipe;$('#recipe-ingredient-form').onsubmit=saveRelation;$('#production-recipe-selector').onchange=e=>selectProduction(e.target.value);$('#production-form').onsubmit=production;
view(location.hash.slice(1)||'home');
